### ISSUE TITLE
Add it to melpa

### ISSUE THREAD

**Issue by francesco-cadei** [Nooby/swagger-mode#2]
I think it's a useful package.

**Comment by Nooby** [comment]
Thank you for your comment. I tried to add it to Melpa, but I need to solve some issues first. Sadly I don't have the time currently to maintain this package. I will try to document these issues small issues and maybe someone has the time to fix them.

**Comment by pataquets** [comment]
@Nooby I would suggest you to leave this issue open in order to let everyone know that those "help wanted" issues are prerequisite to MELPA publishing.

At least, it will prevent from you wasting time, since I was about to post a new "Publish to MELPA" issue :smile:. And maybe with the extra visibility, you get some extra hands.
